apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstagereporinsapp"
  sam: 
  description: "backstagereporinsapp"
  annotations:
    github.com/project-slug: sohemokashi/backstagereporinsapp
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "guests"